{% set name = "pds4_tools" %}
{% set version = "1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pds4_tools-{{ version }}.zip
  sha256: 8e6fdd0a9c4063c9a337b6ed3c52686da4f96bfba2a30e42ec57a6cf25fff459

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 2

requirements:
  host:
    - pip
    - setuptools
    - python {{ python_min }}
  run:
    - numpy
    - python >={{ python_min }},<3.12
    - tk

test:
  imports:
    - pds4_tools
  requires:
    - pip
    - xorg-libx11
    - python {{ python_min }}
  commands:
    - pip check

about:
  home: https://sbnwiki.astro.umd.edu/wiki/Python_PDS4_Tools
  summary: Package to read and display NASA PDS4 data
  description: |
    PDS4 Tools is a package intended to allow easy read-in of NASA PDS4 data
    and meta-data into Python. Included in the package are a read-in API and
    a cross-OS GUI to visualize the products.

    All common PDS4 data products are supported.

    This package is developed by the PDS Small Bodies Node.
  doc_url: https://pdssbn.astro.umd.edu/tools/pds4_tools_docs/current/
  dev_url: https://github.com/Small-Bodies-Node/pds4_tools
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSES

extra:
  recipe-maintainers:
    - LevN0
